import '../models/ad.dart';

String assetPath(int index) {
  final number = ((index - 1) % 8) + 1;
  return 'assets/images/placeholder_ad_${number.toString().padLeft(2, '0')}.png';
}

const _prefectures = ['愛知県', '岐阜県', '三重県', '静岡県'];

String _prefectureFor(int index) => _prefectures[index % _prefectures.length];

final mockAds = <Ad>[
  Ad(
    id: 'ad-001',
    companyName: '名古屋焼肉 炎',
    catchCopy: '週末限定！家族で楽しむ焼肉フェア開催中',
    prText: '国産黒毛和牛を使用した特選コースが今週末限定でお得です。'
        'ご家族でのお食事、会社宴会にも最適。事前予約でドリンクサービス付き。',
    thumbnailAssetPath: assetPath(1),
    category: '飲食店',
    prefecture: _prefectureFor(0),
    startDate: DateTime.now().subtract(const Duration(days: 3)),
    distributionDays: 30,
    hasSpotlightOption: true,
    isAdvertiserAd: true,
    distributorCount: 12,
    viewCount: 1840,
    isDistributing: true,
    advertiserCompanyName: '株式会社炎グループ',
    advertiserUrl: 'https://honoo-yakiniku.example.com',
    advertiserTel: '052-111-2222',
    advertiserContact: '店長 山田',
  ),
  Ad(
    id: 'ad-002',
    companyName: '暮らしの雑貨 ひだまり',
    catchCopy: '春の新生活応援セール開催',
    prText: 'キッチン用品から収納グッズまで最大30%OFF。'
        '駅前店・オンラインショップ同時開催。',
    thumbnailAssetPath: assetPath(2),
    category: '生活雑貨',
    prefecture: _prefectureFor(1),
    startDate: DateTime.now().subtract(const Duration(days: 1)),
    distributionDays: 15,
    isAdvertiserAd: true,
    distributorCount: 8,
    viewCount: 620,
    isDistributing: false,
    advertiserCompanyName: 'ひだまり生活株式会社',
    advertiserUrl: 'https://hidamari.example.com',
    advertiserTel: '052-222-3333',
    advertiserContact: '販売 佐藤',
  ),
  Ad(
    id: 'ad-003',
    companyName: 'すぐ駆けつけ修理 24',
    catchCopy: '水漏れ・電気トラブル即日対応',
    prText: '愛知県内どこでも最短60分で駆けつけ。'
        '見積もり無料、深夜早朝も対応可能です。',
    thumbnailAssetPath: assetPath(3),
    category: '生活トラブル・修理',
    prefecture: _prefectureFor(2),
    startDate: DateTime.now(),
    distributionDays: 20,
    hasSpotlightOption: true,
    isAdvertiserAd: true,
    distributorCount: 15,
    viewCount: 980,
    isDistributing: true,
    advertiserCompanyName: '株式会社すぐ駆けつけ',
    advertiserUrl: 'https://sugu24.example.com',
    advertiserTel: '0120-000-024',
    advertiserContact: '受付 鈴木',
  ),
  Ad(
    id: 'ad-004',
    companyName: 'おうちケアサポート',
    catchCopy: '訪問介護・家事代行の無料相談会',
    prText: 'ご家族の負担を軽減する訪問サービスをご提案。'
        '初回相談・お試しプランをご用意しています。',
    thumbnailAssetPath: assetPath(4),
    category: '家事代行・ケア',
    prefecture: _prefectureFor(3),
    startDate: DateTime.now().add(const Duration(days: 2)),
    distributionDays: 25,
    isAdvertiserAd: true,
    distributorCount: 5,
    viewCount: 210,
    isDistributing: false,
    advertiserCompanyName: 'おうちケア株式会社',
    advertiserUrl: 'https://ouchi-care.example.com',
    advertiserTel: '052-333-4444',
    advertiserContact: '相談員 田中',
  ),
  Ad(
    id: 'ad-005',
    companyName: 'リフォーム工房 匠',
    catchCopy: 'キッチンリフォーム相談会実施中',
    prText: '水回りリフォームのご相談受付中。'
        '3Dシミュレーション無料、補助金申請もサポート。',
    thumbnailAssetPath: assetPath(5),
    category: 'リフォーム',
    prefecture: _prefectureFor(4),
    startDate: DateTime.now().subtract(const Duration(days: 10)),
    distributionDays: 45,
    isAdvertiserAd: true,
    distributorCount: 9,
    viewCount: 1340,
    isDistributing: true,
    wasDistributed: true,
    advertiserCompanyName: '株式会社匠リフォーム',
    advertiserUrl: 'https://takumi-reform.example.com',
    advertiserTel: '052-444-5555',
    advertiserContact: '設計 伊藤',
  ),
  Ad(
    id: 'ad-006',
    companyName: 'エコ回収サービス',
    catchCopy: '不用品回収・粗大ゴミ処分キャンペーン',
    prText: '引越し・遺品整理にも対応。見積もり後の追加料金なし。',
    thumbnailAssetPath: assetPath(6),
    category: '不用品回収',
    prefecture: _prefectureFor(5),
    startDate: DateTime.now().subtract(const Duration(days: 5)),
    distributionDays: 10,
    isAdvertiserAd: true,
    distributorCount: 7,
    viewCount: 450,
    isDistributing: false,
    advertiserCompanyName: 'エコ回収株式会社',
    advertiserUrl: 'https://eco-kaishu.example.com',
    advertiserTel: '052-555-6666',
    advertiserContact: '営業 高橋',
  ),
  Ad(
    id: 'ad-007',
    companyName: 'スタディラボ進学塾',
    catchCopy: '春期講習・無料体験授業受付中',
    prText: '小中学生向け個別指導。成果に応じたカリキュラム設計。',
    thumbnailAssetPath: assetPath(7),
    category: '教育・スクール',
    prefecture: _prefectureFor(6),
    startDate: DateTime.now(),
    distributionDays: 30,
    hasSpotlightOption: true,
    distributorCount: 11,
    viewCount: 760,
    isDistributing: true,
    advertiserCompanyName: 'スタディラボ株式会社',
    advertiserUrl: 'https://study-lab.example.com',
    advertiserTel: '052-666-7777',
    advertiserContact: '教室長 渡辺',
  ),
  Ad(
    id: 'ad-008',
    companyName: '自然食品マルシェ',
    catchCopy: '国産オーガニック野菜の定期便',
    prText: '契約者限定で初回半額。無農薬・減農薬野菜を産地直送。',
    thumbnailAssetPath: assetPath(8),
    category: '健康・食品',
    prefecture: _prefectureFor(7),
    startDate: DateTime.now().subtract(const Duration(days: 2)),
    distributionDays: 20,
    distributorCount: 6,
    viewCount: 390,
    isDistributing: false,
    advertiserCompanyName: 'マルシェ食品株式会社',
    advertiserUrl: 'https://marche-organic.example.com',
    advertiserTel: '052-777-8888',
    advertiserContact: '広報 中村',
  ),
  Ad(
    id: 'ad-009',
    companyName: 'さくら内科クリニック',
    catchCopy: '健康診断・予防接種のご案内',
    prText: '平日夜間診療対応。インフルエンザ予防接種予約受付中。',
    thumbnailAssetPath: assetPath(1),
    category: 'クリニック',
    prefecture: _prefectureFor(8),
    startDate: DateTime.now().add(const Duration(days: 1)),
    distributionDays: 15,
    distributorCount: 4,
    viewCount: 180,
    isDistributing: false,
    advertiserCompanyName: '医療法人さくら会',
    advertiserUrl: 'https://sakura-clinic.example.com',
    advertiserTel: '052-888-9999',
    advertiserContact: '受付 小林',
  ),
  Ad(
    id: 'ad-010',
    companyName: 'リラクゼーションサロン 癒',
    catchCopy: '初回限定アロマトリートメント30%OFF',
    prText: '完全予約制のプライベートサロン。'
        '疲労回復・肩こり改善コースが人気です。',
    thumbnailAssetPath: assetPath(2),
    category: '美容・リラクゼーション',
    prefecture: _prefectureFor(9),
    startDate: DateTime.now().subtract(const Duration(days: 7)),
    distributionDays: 25,
    distributorCount: 10,
    viewCount: 1120,
    isDistributing: true,
    wasDistributed: true,
    advertiserCompanyName: '癒サロン株式会社',
    advertiserUrl: 'https://iyashi-salon.example.com',
    advertiserTel: '052-999-0000',
    advertiserContact: 'オーナー 松本',
  ),
  Ad(
    id: 'ad-011',
    companyName: 'モードハウス青山',
    catchCopy: '新作春コレクション先行予約',
    prText: 'トレンドの春物アパレルを先行予約受付。会員限定特典あり。',
    thumbnailAssetPath: assetPath(3),
    category: 'アパレル・雑貨',
    prefecture: _prefectureFor(10),
    startDate: DateTime.now(),
    distributionDays: 35,
    distributorCount: 8,
    viewCount: 540,
    isDistributing: false,
    advertiserCompanyName: 'モードハウス株式会社',
    advertiserUrl: 'https://mode-aoyama.example.com',
    advertiserTel: '052-101-2020',
    advertiserContact: '店舗 木村',
  ),
  Ad(
    id: 'ad-012',
    companyName: 'カフェ・ド・ナゴヤ',
    catchCopy: 'モーニングセット300円から',
    prText: '駅近の落ち着いたカフェ空間。テイクアウトも対応。',
    thumbnailAssetPath: assetPath(4),
    category: '飲食店',
    prefecture: _prefectureFor(11),
    startDate: DateTime.now().subtract(const Duration(days: 20)),
    distributionDays: 10,
    distributorCount: 14,
    viewCount: 2100,
    isDistributing: true,
    wasDistributed: true,
    advertiserCompanyName: 'カフェドナゴヤ株式会社',
    advertiserUrl: 'https://cafe-nagoya.example.com',
    advertiserTel: '052-202-3030',
    advertiserContact: 'マネージャー 吉田',
  ),
  Ad(
    id: 'ad-013',
    companyName: 'ガス屋さん自社広告',
    catchCopy: 'ガス機器点検キャンペーン実施中',
    prText: '会員様限定でガス機器の安全点検を無料実施。お気軽にお申し込みください。',
    thumbnailAssetPath: assetPath(5),
    category: '生活トラブル・修理',
    prefecture: _prefectureFor(12),
    startDate: DateTime.now().subtract(const Duration(days: 1)),
    distributionDays: 60,
    distributorCount: 20,
    viewCount: 3200,
    isDistributing: true,
    isOwnAd: true,
    isAdvertiserAd: true,
    advertiserCompanyName: '株式会社○○ガス',
    advertiserUrl: 'https://gas-company.example.com',
    advertiserTel: '0120-846-722',
    advertiserContact: '広報 けんじゃ',
  ),
  Ad(
    id: 'ad-014',
    companyName: 'Cluppo FC ジュニア',
    catchCopy: '新入部員・スポンサー募集中',
    prText: '地域の子どもたちを応援するクラブチームです。'
        '部員・スポンサー・サポーターを無料で募集しています。',
    thumbnailAssetPath: assetPath(6),
    category: '教育・スクール',
    prefecture: _prefectureFor(13),
    startDate: DateTime.now(),
    distributionDays: 90,
    hasSpotlightOption: true,
    distributorCount: 18,
    viewCount: 890,
    isDistributing: true,
    advertiserCompanyName: 'Cluppoスポーツクラブ',
    advertiserUrl: 'https://cluppo.example.com',
    advertiserTel: '052-303-4040',
    advertiserContact: 'コーチ 青木',
  ),
  Ad(
    id: 'ad-015',
    companyName: 'パン工房 麦の香',
    catchCopy: '毎朝焼きたてパンをお届け',
    prText: '地元小麦使用の手作りパン。店頭販売・法人向け卸売対応。',
    thumbnailAssetPath: assetPath(7),
    category: '飲食店',
    prefecture: _prefectureFor(14),
    startDate: DateTime.now().subtract(const Duration(days: 15)),
    distributionDays: 20,
    distributorCount: 6,
    viewCount: 670,
    isDistributing: false,
    wasDistributed: true,
    advertiserCompanyName: '麦の香ベーカリー',
    advertiserUrl: 'https://mugi-bakery.example.com',
    advertiserTel: '052-404-5050',
    advertiserContact: '店主 石井',
  ),
  Ad(
    id: 'ad-016',
    companyName: 'スマートホーム設計',
    catchCopy: 'IoT住宅の無料ショールーム見学',
    prText: 'スマートロック・太陽光・蓄電池のトータル提案。',
    thumbnailAssetPath: assetPath(8),
    category: 'リフォーム',
    prefecture: _prefectureFor(15),
    startDate: DateTime.now().add(const Duration(days: 5)),
    distributionDays: 30,
    distributorCount: 3,
    viewCount: 120,
    isDistributing: false,
    advertiserCompanyName: 'スマートホーム株式会社',
    advertiserUrl: 'https://smart-home.example.com',
    advertiserTel: '052-505-6060',
    advertiserContact: '設計 森',
  ),
  Ad(
    id: 'ad-017',
    companyName: 'フィットネスジム ACTIVE',
    catchCopy: '入会金無料キャンペーン',
    prText: 'パーソナルトレーニング・グループレッスン充実。',
    thumbnailAssetPath: assetPath(1),
    category: '健康・食品',
    prefecture: _prefectureFor(16),
    startDate: DateTime.now().subtract(const Duration(days: 4)),
    distributionDays: 25,
    distributorCount: 9,
    viewCount: 830,
    isDistributing: true,
    advertiserCompanyName: 'ACTIVEフィットネス',
    advertiserUrl: 'https://active-gym.example.com',
    advertiserTel: '052-606-7070',
    advertiserContact: 'フロント 原田',
  ),
  Ad(
    id: 'ad-018',
    companyName: 'ペットケアハウス',
    catchCopy: 'ペットホテル・トリミングセット割',
    prText: 'お留守番中も安心。トリミングとホテルをセットでお得に。',
    thumbnailAssetPath: assetPath(2),
    category: '家事代行・ケア',
    prefecture: _prefectureFor(17),
    startDate: DateTime.now(),
    distributionDays: 15,
    distributorCount: 5,
    viewCount: 290,
    isDistributing: false,
    advertiserCompanyName: 'ペットケア株式会社',
    advertiserUrl: 'https://pet-care.example.com',
    advertiserTel: '052-707-8080',
    advertiserContact: 'スタッフ 村上',
  ),
  Ad(
    id: 'ad-019',
    companyName: '地域密着 整骨院',
    catchCopy: '初診料無料・交通事故治療対応',
    prText: '保険適用・自費メニューご相談ください。土日も診療。',
    thumbnailAssetPath: assetPath(3),
    category: 'クリニック',
    prefecture: _prefectureFor(18),
    startDate: DateTime.now().subtract(const Duration(days: 30)),
    distributionDays: 30,
    distributorCount: 7,
    viewCount: 1560,
    isDistributing: true,
    wasDistributed: true,
    advertiserCompanyName: '整骨院グループ',
    advertiserUrl: 'https://seikotsu.example.com',
    advertiserTel: '052-808-9090',
    advertiserContact: '院長 藤田',
  ),
  Ad(
    id: 'ad-020',
    companyName: 'アートスクール 創',
    catchCopy: '子ども向け絵画教室 体験レッスン無料',
    prText: '創造力を育む少人数制レッスン。材料費込みの体験会実施中。',
    thumbnailAssetPath: assetPath(4),
    category: '教育・スクール',
    prefecture: _prefectureFor(19),
    startDate: DateTime.now().subtract(const Duration(days: 60)),
    distributionDays: 30,
    distributorCount: 4,
    viewCount: 410,
    isDistributing: false,
    isAdvertiserAd: true,
    advertiserCompanyName: 'アートスクール創',
    advertiserUrl: 'https://art-sou.example.com',
    advertiserTel: '052-909-0101',
    advertiserContact: '講師 岡田',
  ),
  Ad(
    id: 'own-ad-001',
    companyName: '自社広告：春の安全点検',
    catchCopy: '会員様限定・ガス機器安全点検無料',
    prText: 'お住まいのガス機器を無料点検。お申し込みはお電話またはWEBから。',
    thumbnailAssetPath: assetPath(5),
    category: '生活トラブル・修理',
    prefecture: '愛知県',
    isOwnAd: true,
    isAdvertiserAd: true,
    startDate: DateTime.now().subtract(const Duration(days: 2)),
    distributionDays: 45,
    distributorCount: 22,
    viewCount: 4100,
    isDistributing: true,
    advertiserCompanyName: '株式会社○○ガス',
    advertiserUrl: 'https://gas-company.example.com',
    advertiserTel: '0120-846-722',
    advertiserContact: '広報 けんじゃ',
  ),
  Ad(
    id: 'own-ad-002',
    companyName: '自社広告：新サービス案内',
    catchCopy: '会員アプリで料金照会がもっと簡単に',
    prText: '新しい会員アプリをリリースしました。料金照会・お支払いがスマホで完結。',
    thumbnailAssetPath: assetPath(6),
    category: '生活雑貨',
    prefecture: '愛知県',
    isOwnAd: true,
    isAdvertiserAd: true,
    startDate: DateTime.now().add(const Duration(days: 3)),
    distributionDays: 30,
    distributorCount: 0,
    viewCount: 0,
    isDistributing: false,
    advertiserCompanyName: '株式会社○○ガス',
    advertiserUrl: 'https://gas-company.example.com',
    advertiserTel: '0120-846-722',
    advertiserContact: '広報 けんじゃ',
  ),
];

/// Repository 初期データ（単一ソース）
final initialAds = List<Ad>.from(mockAds);

/// 後方互換
final advertiserAds = initialAds
    .where((ad) => ad.isAdvertiserAd || ad.isOwnAd)
    .toList();

final ownAds = initialAds.where((ad) => ad.isOwnAd).toList();

/// サムネイル選択用プレースホルダー一覧
final thumbnailAssetOptions = List.generate(
  8,
  (index) => assetPath(index + 1),
);
